version: "3.3"
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "typebot"
      POSTGRES_PASSWORD: "typebot"
volumes:
  db_data:
